travis:
  secure:
    BINSTAR_TOKEN: ZchoQHCSftzP6hfJQWt4oppArYcORivYlYym2qZe6wyUcgiyCnfbvdd2n1/W26L43CTcTUfF8nO8IZleyzCEEeH96F+xPOykymS1SybkDZJnw6krID8vgU6yl6Hy38yMhP/o66pmtREri0D+ETkEioCorKTwP8sbZU6Kxp6qT5cAi+ifGJvaH2AvEG/kzhNgWWugH4qNi4D+L8J1qWqeoixLz8xkvN2ZDOpTxaU7YU0EpVME0hj2r024ksMn7UvsYaM2iGg+Xw5llwib1U05d6TNLDA4GOWig5d9Qqpfe0Iy5b9Eo331pVEQB8r+2Xtd1+3q7YvFfPeCaI4FYMH5bkgXwoj2egvOyrTUqod6gKdQlNEaKMW/9Gwr6vh+7he9zykcNW3eNf0QHrKw9swx+vWYMYKEPsStNsNi1mepDTl4LX8dv0FLcd/vvxB2PvsZ3aOb1uNPUQvVMFxFXT/1uuEB4suT7BeeS501hLkg+almajLT6+/xz/5N2+ylzWDWFwL9bqrd3iAb1qK+UTcv/ef9PynbPzLwxo9MJZ8iGOcwtt640JDDh0CCpuL1yibiCcxrssBu7R66JrJ5Dn78rlYsW9uyN4uJkocdv91+PjdmyvMxXE3krBN5We+sGIjGU6yQ5vDSpus1lHI8qJntAN4gmIQih66eUQN4FKkqEA8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
